using System;
using System.Collections.Generic;
using System.Diagnostics;
using The72Network.Web.Shared;

namespace The72Newtork.Web.Shared.Utilities
{
  public static class Util
  {
    public static List<string> ListOfProfessions
    {
      get
      {
        return new List<string>
        {
          "Accountant",
          "Actor/Actress",
          "Architect",
          "Astronomer",
          "Author",
          "Baker",
          "Bricklayer",
          "Bus driver",
          "Butcher",
          "Carpenter",
          "Chef/Cook",
          "Cleaner",
          "Dentist",
          "Designer",
          "Doctor",
          "Dustman/Refuse collector",
          "Electrician",
          "Engineer",
          "Factory worker",
          "Farmer",
          "Fireman/Fire fighter",
          "Fisherman",
          "Florist",
          "Gardener",
          "Hairdresser",
          "Journalist",
          "Judge",
          "Lawyer",
          "Lecturer",
          "Librarian",
          "Lifeguard",
          "Mechanic",
          "Model",
          "Newsreader",
          "Nurse",
          "Optician",
          "Painter",
          "Pharmacist",
          "Photographer",
          "Pilot",
          "Plumber",
          "Politician",
          "Policeman/Policewoman",
          "Postman",
          "Real estate agent",
          "Receptionist",
          "Scientist",
          "Secretary",
          "Shop assistant",
          "Software Engineer",
          "Soldier",
          "Tailor",
          "Taxi driver",
          "Teacher",
          "Translator",
          "Traffic warden",
          "Travel agent",
          "Veterinary doctor (Vet)",
          "Waiter/Waitress",
          "Window cleaner",
        };
      }
    }

    public static List<string> ListOfCountries()
    {
      return new List<string>
      {
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo, the Democratic Republic of the",
        "Cook Islands",
        "Costa Rica",
        "Cote D'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and Mcdonald Islands",
        "Holy See (Vatican City State)",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Republic of",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, Democratic People's Republic of",
        "Korea, Republic of",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Macedonia, the Former Yugoslav Republic of",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Federated States of",
        "Moldova, Republic of",
        "Monaco",
        "Mongolia",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "Netherlands Antilles",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestinian Territory, Occupied",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia and Montenegro",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan, Province of China",
        "Tajikistan",
        "Tanzania, United Republic of",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Viet Nam",
        "Virgin Islands, British",
        "Virgin Islands, US",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe"
      };
    }

    public static IList<string> ListOfAdmins(string adminsStringFromWebSettings)
    {
      string adminsString = string.Empty;
      try
      {
        adminsString = Environment.GetEnvironmentVariable(Constants.Admin_Usernames);
      }
      catch (Exception ex)
      {
        Trace.TraceError("Failed to retrieve environment settings with ex : {0}", ex);
      }

      IList<string> adminList;
      if (!string.IsNullOrWhiteSpace(adminsString))
      {
        adminList = adminsString.Split(Constants.Admin_Usernames_Delimiter);
      }
      else
      {
        // Only if EnvironmentSettings was not found we use app settings to get admins.
        adminList = adminsStringFromWebSettings.Split(Constants.Admin_Usernames_Delimiter);
      }

      return adminList;
    }
  }
}