// <auto-generated />
namespace The72Network.Web.StorageAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AssemblySeparation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssemblySeparation));
        
        string IMigrationMetadata.Id
        {
            get { return "201607021735072_Assembly Separation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
